version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,TRACE://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,TRACE:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - "8080:8080"
    networks:
      - kafka-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    networks:
      - kafka-network

  kafka-init:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Criando tópicos Kafka..."
        kafka-topics --create --topic order-received-topic --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
        kafka-topics --create --topic order-duplicate-topic --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
        kafka-topics --create --topic order-processing-topic --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
        kafka-topics --create --topic order-processed-topic --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
        kafka-topics --create --topic order-send-topic --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
        kafka-topics --create --topic order-sent-topic --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
        echo "Tópicos criados com sucesso!"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
