server:
  port: 8084

spring:
  application:
    name: order-query
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true